const langArr = {
    en: {
      about: 'About us',
      contact: 'Contacts',
      uz: 'Uzbekistan',
      dream: 'Find your dream house with',
      agency: 'A real estate agency that cares about its clients',
      learn: 'Learn More',
      learn2: 'Learn More',
      learn3:'Learn More',
      learn4:'Learn More',
      why: 'Why choose us?',
      service: 'Convenient service',
      service__p:'Our real estate catalog contains more than 1,000 real estate objects for the sale and purchase of apartments, houses, new buildings, commercial real estate. Convenient search and daily updates of real estate objects will help you make the right choice!',
      best: 'The best specialists',
      best__p: 'Save up to 30% time and money! We will help you choose a property, improve your living conditions or make a profitable investment, taking into account your requirements, wishes and opportunities. In the shortest possible time, we will make a selection of relevant objects, resolve all issues with paperwork and notarization. We appreciate your time!',
      guarn:'Quality assurance',
      guarn__p:'Competent execution of preliminary agreements, legal verification of the right of establishing documents, preparation and support of the transaction to the notary. We guarantee the safe conduct of any transaction with the benefit / benefit for the client from specialists with many years of experience in this field.',
      aboutus:'About us',
      abouth2:'Short information',
      about__h3:'Real estate agency "Comfort home"',
      about__p:'Real estate agency "Keys of Tashkent" is an organization in which you will receive all possible types of real estate services: purchase and sale, rent, exchange of residential and commercial real estate. We cooperate with both individuals and legal entities. In our real estate catalog you can find objects for every taste, and highly qualified employees will provide legally correct support and execution of all types of transactions, since experience is of great importance. And most importantly, our agency will take on the responsibility of real estate appraisal, i.е. will check its "purity" in the legal sense: the correct registration of ownership; readiness of all documents for the transaction. And also, according to your order, if necessary, a title examination can be carried out. We save your time!', 
      contacts:'Contacts',
      contacts__h2:'Contact us!',
      contacts__h3:'You can contact us via',
      contacts__p1:'Our phone numbers',
      contacts__p2:'Our mail',
      contacts__p3:'Our telegram channel',
      contacts__p4:'Our instagram',
      contacts__p11:'+998 99 0040700',
      contacts__p12:'+998 94 4220620',
      contacts__p21:'Our mail, click',
      contacts__p31:'Comfort home',
      contacts__p41:'comfort_home.agency',
    },
   
    ru: {
      about: 'О нас',
      contact: 'Контакты',
      uz: 'Узбекистан',
      dream: 'Найдите дом своей мечты с',
      agency: 'Агенство недвижимости которая заботиться о своих клиентах',
      learn: 'Узнать больше',
      learn2: 'Узнать больше',
      learn3:'Узнать больше',
      learn4:'Узнать больше',
      why: 'Почему выбирают нас?',
      service: 'Удобный сервис',
      service__p:'В нашем каталоге недвижимости более 1 000 объектов недвижимост по купле-продаже квартир, домов, новостроек, коммерческой недвижимости. Удобный поиск и ежедневное обновление объектов недвижимости поможет Вам сделать правильный выбор!',
      best: 'Лучшие специалисты',
      best__p:'Экономьте до 30% времени и денег! Поможем подобрать недвижимость, улучшить жилищные условия или выгодно инвестировать с учетом ваших требований, пожеланий и возможностей. В кратчайшие сроки сделаем подбор актуальных объектов, решим все вопросы с оформлением документов и нотариальным заверением. Мы ценим Ваше время!',
      guarn:'Гарантия качества',
      guarn__p:'Грамотное оформление предварительных соглашений, юридическая проверка право устанавливающих документов, подготовка и сопровождение сделки до нотариуса. Мы гарантируем безопасное проведение любой сделки с выгодой/пользой для клиента от специалистов с многолетним опытом работы в данной сфере.',
      aboutus:'О нас',
      abouth2:'Краткая информация',
      about__h3:'Агентство недвижимости "Comfort home"',
      about__p:'Агентство недвижимости «Ключи Ташкента» — организация, в которой Вы получите все возможные виды риэлторских услуг: купля-продажа, аренда, обмен жилого и коммерческого недвижимого имущества. Мы сотрудничаем как с физическими, так и с юридическими лицами. В нашем каталоге недвижимости Вы сможете найти объекты на любой вкус, а высококвалифицированные сотрудники предоставят юридически правильное сопровождение и оформление всех видов сделок, так как опыт имеет большое значение. И самое главное — наше агентство возьмет на себя обязательства по оценке недвижимости, т.е. сделает проверку ее «чистоты» в юридическом смысле: правильное оформление права собственности; готовность всех документов для проведения сделки. А также по Вашему заказу, если есть необходимость, может быть проведена и правоустанавливающая экспертиза. Мы бережем Ваше время!',
      contacts:'Контакты',
      contacts__h2:'Свяжитесь с нами!',
      contacts__h3:'Вы можете связаться с нами через',
      contacts__p1:'Наши номера телефона',
      contacts__p2:'Наша почта',
      contacts__p3:'Наш телеграм канал',
      contacts__p4:'Наш инстаграм',
      contacts__p11:'+998 99 0040700',
      contacts__p12:'+998 94 4220620',
      contacts__p21:'Наш гугл аккаунт',
      contacts__p31:'Comfort home',
      contacts__p41:'comfort_home.agency',
    },
    };